import { createAsyncThunk, createSlice } from "@reduxjs/toolkit";
import axios from "axios";

export interface anilistState {
  response: string;
}

const initialState: anilistState = {
  response: "",
};

type AnilistQueryBody = {
  token: string;
  manga_id: string;
  manga_status: string;
};

export interface StatusDictionary {
  [mangadexStatus: string]: string;
}

const anilistStatuses: StatusDictionary = {
  reading: "CURRENT",
  completed: "COMPLETED",
  plan_to_read: "PLANNING",
  dropped: "DROPPED",
  on_hold: "PAUSED",
};

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
/* Query to modify the list
mutation($mediaId: Int, $status: MediaListStatus) { : Literal['mutation($mediaId
    SaveMediaListEntry (mediaId: $mediaId, status: $status) {
        id
        status
    }
}
 */
export const updateMangaListAsync = createAsyncThunk(
  "anilist/mangalist",
  async (body: AnilistQueryBody) => {
    const config = {
      headers: {
        Authorization: "Bearer " + body.token,
        "Content-Type": "application/json",
        Accept: "application/json",
      },
    };
    const mutation_query = `
	mutation($mediaId: Int, $status: MediaListStatus) { 
	    SaveMediaListEntry (mediaId: $mediaId, status: $status) {
		id
		status
	    }
	}	
	  `;
    const variables = {
      mediaId: body.manga_id,
      status: anilistStatuses[body.manga_status],
    };
    const response = await axios.post(
      "https://graphql.anilist.co",
      {
        query: mutation_query,
        variables: variables,
      },
      config
    );
    return response.data;
  }
);

export const anilistSlice = createSlice({
  name: "anilist",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {},
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(updateMangaListAsync.pending, () => {
        console.log("update manga list pending");
      })
      .addCase(updateMangaListAsync.fulfilled, (state, action) => {
        state.response += action.payload;
        console.log("update manga list success");
        //state.token = action.payload.token.session;
      })
      .addCase(updateMangaListAsync.rejected, (state, action) => {
        console.log("failed to update manga list", state, action);
      });
  },
});

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.anilist.value)`
//export const selectCount = (state: RootState) => state.anilist.token;

// We can also write thunks by hand, which may contain both sync and async logic.
// Here's an example of conditionally dispatching actions based on current state.

export default anilistSlice.reducer;
